CREATE TABLE helsing_employee (
    e_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    employee_firstname TEXT NOT NULL,
    employee_lastname TEXT NOT NULL,
    employee_email TEXT NOT NULL
);

CREATE TABLE helsing_reservestudy (
    rs_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    association TEXT NOT NULL,
    manager_firstname TEXT,
    manager_email TEXT,
    assigned_to INTEGER
        REFERENCES helsing_employee(e_id) ON DELETE CASCADE,
    date_added TIMESTAMP DEFAULT now() NOT NULL,
    fy_end TEXT,
    client_number TEXT,
    date_in_queue TIMESTAMP,
    total_price TEXT,
    csa BOOLEAN,
    scope BOOLEAN,
    retainer BOOLEAN,
    ccrs BOOLEAN,
    hoa_questionnaire BOOLEAN,
    budget BOOLEAN,
    site_plan BOOLEAN,
    reserve_study BOOLEAN,
    annual_review BOOLEAN,
    income_statement BOOLEAN,
    balance_sheet BOOLEAN,
    draft_billed BOOLEAN,
    final_billed BOOLEAN,
    draft_billed_date TIMESTAMP,
    final_billed_date TIMESTAMP,
    additional_notes TEXT
);

CREATE TABLE helsing_sustainment (
    s_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    association TEXT NOT NULL,
    manager_firstname TEXT,
    manager_email TEXT,
    assigned_to INTEGER
        REFERENCES helsing_employee(e_id) ON DELETE CASCADE,
    date_added TIMESTAMP DEFAULT now() NOT NULL,
    fy_end TEXT,
    client_number TEXT,
    total_price TEXT,
    s_contract BOOLEAN,
    retainer BOOLEAN,
    worksheets_yr1 BOOLEAN,
    worksheets_yr2 BOOLEAN,
    worksheets_yr3 BOOLEAN,
    yr1_billed BOOLEAN,
    yr1_billed_date TIMESTAMP,
    yr2_billed BOOLEAN,
    yr2_billed_date TIMESTAMP,
    yr3_billed BOOLEAN,
    yr3_billed_date TIMESTAMP,
    sustainment_letter BOOLEAN,
    additional_notes TEXT
);

CREATE TABLE helsing_timeandmaterial (
    tm_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    association TEXT NOT NULL,
    manager_firstname TEXT,
    manager_email TEXT,
    assigned_to INTEGER
        REFERENCES helsing_employee(e_id) ON DELETE CASCADE,
    date_added TIMESTAMP DEFAULT now() NOT NULL,
    fy_end TEXT,
    client_number TEXT,
    total_price TEXT,
    tm_contract BOOLEAN,
    worksheets BOOLEAN,
    billed BOOLEAN,
    billed_date TIMESTAMP,
    additional_notes TEXT
);
